[tool.poetry]
name = "flaskproject"
version = "0.1.0"
description = ""
authors = ["ihrskyfish <ihr17867950748@126.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
